apiVersion: apps/v1
kind: Deployment
metadata:
  name: clo835-final-app
  namespace: final
  labels:
    appname: app-deployment
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: app-deployment
      component: frontend
  template:
    metadata:
      labels:
        appname: app-deployment
        component: frontend
    spec:
      containers:
      - name: my-app
        image: 103848042406.dkr.ecr.us-east-1.amazonaws.com/my_app
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: static-volume
          mountPath: /app/static
        envFrom:
        - configMapRef:
            name: app-config
      imagePullSecrets:
        - name: creds-final
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-pvc