apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: final
  labels:
    appname: app-deployment
    component: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 81
  selector:
    appname: app-deployment
    component: frontend