apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: final
  labels:
    appname: app-deployment
    component: frontend
spec:
  type: NodePort
  ports:
  - port: 30000
    targetPort: 81
    nodePort: 30000
  selector:
    appname: app-deployment
    component: frontend