apiVersion: apps/v1
kind: Deployment
metadata:
  name: clo835-final-db
  namespace: final
  labels:
    appname: db-deployment
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: db-deployment
      component: backend
  template:
    metadata:
      labels:
        appname: db-deployment
        component: backend
    spec:
      containers:
      - name: my-db
        image: 103848042406.dkr.ecr.us-east-1.amazonaws.com/my_db:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
      imagePullSecrets:
        - name: creds-final
