apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: final
  labels:
    appname: app-deployment
    component: frontend
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi