apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: final
  labels:
    appname: db-deployment
    component: backend
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi